name: â˜„ï¸ ASTEROID ï¸â˜„ï¸

on:
    push:
    workflow_dispatch:
    
jobs:
  ASTEROID:
    runs-on: ubuntu-20.04

    steps:
       - name: ðŸ Set up Python 3.9 ðŸ
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "ðŸš«CANCLE DUPLICATE WORKFLOW RUNSðŸš«"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: â˜¢ï¸ INITIALISING ASTEROID â˜¢ï¸
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Â©ï¸ CLONING REPOSITORY Â©ï¸
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} asteroid
       - name: ðŸ“€ RUNNING ASTEROID SERVER ðŸ“€
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd asteroid
           docker build . -t asteroid
           docker run asteroid
       - name: ðŸ’« LOOP ASTEROID SERVER ðŸ’«
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m " ðŸ’« LOOP ASTEROID SERVER ðŸ’«"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:asteroid
